USE MASTER 
GO

IF DB_ID('BD_PRODUCTOS') IS NOT NULL
BEGIN
	ALTER DATABASE BD_PRODUCTOS SET SINGLE_USER WITH ROLLBACK IMMEDIATE
	DROP DATABASE BD_PRODUCTOS
END
GO

CREATE DATABASE BD_PRODUCTOS
GO

USE BD_PRODUCTOS
GO

SET LANGUAGE SPANISH
GO
SET DATEFORMAT DMY
GO
SET NOCOUNT ON
GO

CREATE TABLE USUARIO(
	ID_USER INT NOT NULL PRIMARY KEY,
	USSERNAME VARCHAR(30),
	PASS VARCHAR(30),
	NOMBRE VARCHAR(50),
	APELLIDO_PATERNO VARCHAR(50),
	APELLIDO_MATERNO VARCHAR(50),
	CORREO VARCHAR(60)
)
GO

INSERT INTO USUARIO VALUES(1,'sebastian-reyes','12345','Sebastián','Reyes','Quiroz','sebastian@gmail.com');
INSERT INTO USUARIO VALUES(2,'pedro-sanchez','abc596','Pedro','Sánchez','Torres','pedro@gmail.com');